replicaCount: 2

image:
  repository: ./genai-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  LOG_LEVEL: info

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: genai.local
      paths:
        - /
  tls: []

cloudProvider: generic