{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "genai.labels" $ | nindent 4 }}
spec:
  # CHOIX AUTOMATIQUE du type de service
  type: {{ if $.Values.global.isCloud }}ClusterIP{{ else }}NodePort{{ end }}
  
  ports:
  - port: {{ $serviceConfig.port }}
    targetPort: {{ $serviceConfig.port }}
    protocol: TCP
    name: http
    
    # NODEPORT UNIQUEMENT en local
    {{- if and (not $.Values.global.isCloud) (hasKey $.Values.servicePorts $serviceName) }}
    nodePort: {{ index $.Values.servicePorts $serviceName }}
    {{- end }}
    
  selector:
    {{- include "genai.selectorLabels" $ | nindent 4 }}
    service: {{ $serviceName }}
    
---
{{- end }}
{{- end }}
